Fix condition where auto raster dpi is set to zero
If the auto raster dpi is zero, the code fails when creating the buffered image with the following error:

java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0

This change prevents that. The value of dpi here is always equal to rasterDpi when originally set to RASTERIZE_DPI_AUTO.